# Generated by Django 5.0.7 on 2024-07-10 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temp', models.FloatField()),
                ('humidity', models.CharField(max_length=10)),
                ('heatindex', models.CharField(max_length=15)),
                ('condition', models.CharField(max_length=20)),
                ('wind_speed', models.CharField(max_length=15)),
                ('gust_speed', models.CharField(max_length=10)),
                ('pressure', models.CharField(max_length=15)),
                ('cloud', models.CharField(max_length=10)),
                ('precip', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
