# Generated by Django 5.0.7 on 2024-07-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_weatherdata_cloud_alter_weatherdata_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='temp',
            field=models.CharField(max_length=50),
        ),
    ]
